#ifndef INCLUDE_AXON_DEBUG_DEFINES
#define INCLUDE_AXON_DEBUG_DEFINES


//#define DEBUG_METRICS
//#define DEBUG_WARNINGS
//#define DEBUG_OBJECT_CREATE_DESTROY

//#define DEBUG_EVENT_MANAGER
//#define DEBUG_EVENT_MANAGER_VERBOSE

//#define DEBUG_KEY_SCANNER
//#define DEBUG_EVENT
//#define DEBUG_MIDI_EVENT
//#define DEBUG_CHANNEL_MIDI_EVENT
//#define DEBUG_CC_MIDI_EVENT
//#define DEBUG_PC_MIDI_EVENT
//#define DEBUG_SONG_SELECT_MIDI_EVENT
//#define DEBUG_SWITCH_EVENT
//#define DEBUG_SYSEX_MIDI_EVENT
//#define DEBUG_MANUFACTURER_SYSEX_MIDI_EVENT
//#define DEBUG_FAS_FRONT_PANEL_CHANGE_EVENT_TYPE
//#define DEBUG_FAS_PRESET_NUMBER_EVENT_TYPE
//#define DEBUG_FAS_TUNER_INFO_EVENT_TYPE
//#define DEBUG_FAS_SCENE_NUMBER_EVENT_TYPE
//#define DEBUG_MIDI_IMPLEMENTATION

//#define DEBUG_ACTION_EVENT_CLIENT
//#define DEBUG_LABEL_DISPLAY_EVENT_CLIENT
//#define DEBUG_LABEL_DISPLAY_EVENT_CLIENT_REDRAW
//#define DEBUG_LATCHING_EVENT_CLIENT
//#define DEBUG_MOMENTARY_EVENT_CLIENT
//#define DEBUG_MOMENTARY_EVENT_CLIENT_JUST_ONOFFS
//#define DEBUG_RADIO_GROUP_EVENT_CLIENT
//#define DEBUG_AXE_FX_XL_PLUS_SYSEX_EVENT_CLIENT

//#define DEBUG_MOMENTARY_SWITCH_ACTION
//#define DEBUG_LATCHING_SWITCH_ACTION
//#define DEBUG_LABEL_DISPLAY_ACTION
//#define DEBUG_LABEL_DISPLAY_REDRAW
//#define DEBUG_RADIO_SWITCH_ACTION
//#define DEBUG_RADIO_SWITCH_GROUP_ACTION
//#define DEBUG_AXE_FX_XL_PLUS_PRESET_BLOCKS_DATA_REQUEST_ACTION
//#define DEBUG_AXE_FX_XL_PLUS_PRESET_NAME_REQUEST_ACTION

//#define DEBUG_DECODER
//#define DEBUG_FAS_MANUFACTURER_DECODER
//#define DEBUG_AXEFX_XL_PLUS_MODEL_DECODER
//#define DEBUG_AXEFX_XL_PLUS_CHECKSUM_DECODER
//#define DEBUG_AXEFX_XL_PLUS_FRONT_PANEL_CHANGE_DECODER
//#define DEBUG_AXEFX_XL_PLUS_PRESET_BLOCKS_DATA_DECODER
//#define DEBUG_AXEFX_XL_PLUS_TUNER_INFO_DECODER
//#define DEBUG_AXEFX_XL_PLUS_PRESET_NUMBER_DECODER
//#define DEBUG_AXEFX_XL_PLUS_PRESET_NAME_DECODER
//#define DEBUG_AXEFX_XL_PLUS_SCENE_NUMBER_DECODER

//#define DEBUG_AXEFX_XL_PLUS_FRONT_PANEL_CHANGE_DECODER_VERBOSE
//#define DEBUG_AXEFX_XL_PLUS_PRESET_BLOCKS_DATA_DECODER_VERBOSE
//#define DEBUG_AXEFX_XL_PLUS_TUNER_INFO_DECODER_VERBOSE
//#define DEBUG_AXEFX_XL_PLUS_PRESET_NUMBER_DECODER_VERBOSE
//#define DEBUG_AXEFX_XL_PLUS_PRESET_NAME_DECODER_VERBOSE
//#define DEBUG_AXEFX_XL_PLUS_SCENE_NUMBER_DECODER_VERBOSE

#endif