#ifndef INCLUDE_AXON_DEBUG_DEFINES
#define INCLUDE_AXON_DEBUG_DEFINES

//#define DEBUG_AXON_EVENT
//#define DEBUG_AXON_MIDI_EVENT
//#define DEBUG_AXON_CHANNEL_MIDI_EVENT
//#define DEBUG_AXON_CC_MIDI_EVENT
//#define DEBUG_AXON_SWITCH_EVENT

//#define DEBUG_AXON_MIDI_IMPLEMENTATION

//#define DEBUG_AXON_EVENT_MANAGER

//#define DEBUG_AXON_ACTION_CLIENT
//#define DEBUG_AXON_LABEL_DISPLAY
//#define DEBUG_AXON_LABEL_DISPLAY_REDRAW
//#define DEBUG_AXON_LATCHING
//#define DEBUG_AXON_MOMENTARY
//#define DEBUG_AXON_MOMENTARY_JUST_ONOFFS
//#define DEBUG_AXON_RADIO_GROUP

//#define DEBUG_METRICS
#define DEBUG_WARNINGS



#endif