#ifndef INCLUDE_AXON_DEBUG_DEFINES
#define INCLUDE_AXON_DEBUG_DEFINES

//#define DEBUG_AXON_EVENT
//#define DEBUG_AXON_MIDI_EVENT
//#define DEBUG_AXON_CHANNEL_MIDI_EVENT
//#define DEBUG_AXON_CC_MIDI_EVENT
//#define DEBUG_AXON_SWITCH_EVENT
//#define DEBUG_AXON_SYSEX_MIDI_EVENT
//#define DEBUG_AXON_MANUFACTURER_SYSEX_MIDI_EVENT
//#define DEBUG_FAS_FRONT_PANEL_CHANGE_EVENT_TYPE
//#define DEBUG_FAS_PRESET_NUMBER_EVENT_TYPE
//#define DEBUG_FAS_TUNER_INFO_EVENT_TYPE

//#define DEBUG_AXON_MIDI_IMPLEMENTATION

//#define DEBUG_AXON_EVENT_MANAGER
//#define DEBUG_AXON_ACTION_CLIENT
//#define DEBUG_AXON_AXE_FX_FRONT_PANEL_CHANGE_LOGIC_EVENT_CLIENT
//#define DEBUG_AXON_LABEL_DISPLAY
//#define DEBUG_AXON_LABEL_DISPLAY_REDRAW
//#define DEBUG_AXON_LATCHING
//#define DEBUG_AXON_MOMENTARY
//#define DEBUG_AXON_MOMENTARY_JUST_ONOFFS
//#define DEBUG_AXON_RADIO_GROUP_EVENT_CLIENT
//#define DEBUG_AXON_AXEFX_SCENE_CHANGE_LOGIC_EVENT_CLIENT
//#define DEBUG_AXON_AXE_FX_SYSEX_EVENT_CLIENT

//#define DEBUG_METRICS
#define DEBUG_WARNINGS


//#define DEBUG_AXON_AXE_FX_XL_PLUS_PRESET_BLOCKS_DATA_REQUEST_ACTION
#//define DEBUG_AXON_AXE_FX_XL_PLUS_PRESET_NAME_REQUEST_ACTION


//#define DEBUG_AXON_DECODER
//#define DEBUG_AXON_FAS_MANUFACTURER_DECODER_TYPE
//#define DEBUG_AXON_AXEFX_XL_PLUS_MODEL_DECODER_TYPE
//#define DEBUG_AXON_AXEFX_XL_PLUS_CHECKSUM_DECODER_TYPE
//#define DEBUG_AXON_AXEFX_XL_PLUS_FRONT_PANEL_CHANGE_DECODER_TYPE
//#define DEBUG_AXON_AXEFX_XL_PLUS_PRESET_BLOCKS_DATA_DECODER_TYPE
//#define DEBUG_AXON_AXEFX_XL_PLUS_TUNER_INFO_DECODER_TYPE
//#define DEBUG_AXON_AXEFX_XL_PLUS_PRESET_NUMBER_DECODER_TYPE
//#define DEBUG_AXON_AXEFX_XL_PLUS_PRESET_NAME_DECODER_TYPE
//#define DEBUG_AXON_AXEFX_XL_PLUS_SCENE_NUMBER_DECODER_TYPE

//#define DEBUG_AXON_AXEFX_XL_PLUS_FRONT_PANEL_CHANGE_DECODER_TYPE_VERBOSE
//#define DEBUG_AXON_AXEFX_XL_PLUS_PRESET_BLOCKS_DATA_DECODER_TYPE_VERBOSE
//#define DEBUG_AXON_AXEFX_XL_PLUS_TUNER_INFO_DECODER_TYPE_VERBOSE
//#define DEBUG_AXON_AXEFX_XL_PLUS_PRESET_NUMBER_DECODER_TYPE_VERBOSE
//#define DEBUG_AXON_AXEFX_XL_PLUS_PRESET_NAME_DECODER_TYPE_VERBOSE
//#define DEBUG_AXON_AXEFX_XL_PLUS_SCENE_NUMBER_DECODER_TYPE_VERBOSE

#endif